config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/about'

  get 'pages/gallery'

  get 'pages/contact'

  get 'pages/instagram'

  resources :posts
  root "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, stretches: 12

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="https://fonts.googleapis.com/css?family=Oswald:700|Patua+One|Roboto+Condensed:700" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<section id="contact" class="content-section text-center">
        <div class="contact-section">
            <div class="container">
              <h2>Contact Us</h2>
              <p>Feel free to shout us by feeling the contact form or visiting our social network sites like Fackebook,Whatsapp,Twitter.</p>
              <div class="row">
                <div class="col-md-8 col-md-offset-2">
                  <form class="form-horizontal">
                    <div class="form-group">
                      <label for="exampleInputName2">Name</label>
                      <input type="text" class="form-control" id="exampleInputName2" placeholder="Jane Doe">
                    </div>
                    <div class="form-group">
                      <label for="exampleInputEmail2">Email</label>
                      <input type="email" class="form-control" id="exampleInputEmail2" placeholder="jane.doe@example.com">
                    </div>
                    <div class="form-group ">
                      <label for="exampleInputText">Your Message</label>
                     <textarea  class="form-control" placeholder="Description"></textarea> 
                    </div>
                    <button type="submit" class="btn btn-default">Send Message</button>
                  </form>

                  <hr>
                    <h3>Our Social Sites</h3>
                  <ul class="list-inline banner-social-buttons">
                    <li><a href="#" class="btn btn-default btn-lg"><i class="fa fa-twitter"> <span class="network-name">Twitter</span></i></a></li>
                    <li><a href="#" class="btn btn-default btn-lg"><i class="fa fa-facebook"> <span class="network-name">Facebook</span></i></a></li>
                    <li><a href="#" class="btn btn-default btn-lg"><i class="fa fa-youtube-play"> <span class="network-name">Youtube</span></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
        </div>
      </section>

app/views/pages/gallery.html.erb
<h1>Pages#gallery</h1>
<p>Find me in app/views/pages/gallery.html.erb</p>
<div class='measurements'>
  
  <div class="body">
  </div>

  
  <div id="header">
    <h1>Measurements page</h1>
    <p>Here you will find every measurement for your cooking needs</p>
  </div>
  
  <div id="f1_container">
   <div id="f1_card" class="shadow">
    <div class="front face">
      <p>1 Gallon</p>
     <%= image_tag "flower.jpeg" %>
    </div>
    <div class="back face center">
      <p>1 Gallon</p>
      <p>has--4 quarts, 8 pints, 16 cups, 128 ounces, 3.8 liters</p>
    </div>
   </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  
  <div id="f1_container">
   <div id="f1_card" class="shadow">
    <div class="front face">
      <p>1 Quart</p>
     <%= image_tag "gecko.jpeg" %>
    </div>
    <div class="back face center">
      <p>1 Quart</p>
      <p>has--2 pints, 4 cups, 32 ounces, .95 liters</p>
    </div>
   </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  
  <div id="f1_container">
   <div id="f1_card" class="shadow">
    <div class="front face">
      <p>1 Pint</p>
     <%= image_tag "kitty.jpeg" %>
    </div>
    <div class="back face center">
      <p>1 Pint</p>
      <p>has--2 cups, 16 ounces, 480 millilleters</p>
    </div>
   </div>
  </div>
  
  <div id="f1_container">
   <div id="f1_card" class="shadow">
    <div class="front face">
      <p>1 cup</p>
     <%= image_tag "leaf.jpeg" %>
    </div>
    <div class="back face center">
      <p>1 cup</p>
      <p>8 ounces, 240 millilleters</p>
    </div>
   </div>
  </div>
  
  <div id="f1_container">
   <div id="f1_card" class="shadow">
    <div class="front face">
      <p>1/4 cup</p>
     <%= image_tag "butterfly.jpeg" %>
    </div>
    <div class="back face center">
      <p>1/4 cup</p>
      <p>4 Tablespoons, 12 teaspoons, 2 ounces, 60 millilleters</p>
    </div>
   </div>
  </div>
  
  <div id="f1_container">
   <div id="f1_card" class="shadow">
    <div class="front face">
      <p>1 TBLspoon</p>
     <%= image_tag "butterfly.jpeg" %>
    </div>
    <div class="back face center">
      <p>1 TBLspoon</p>
      <p>3 teaspoons, 1/2 fluid ounce, 15 millilleters</p>
    </div>
   </div>
  </div>

app/views/pages/instagram.html.erb
<h1>Pages#instagram</h1>
<p>Find me in app/views/pages/instagram.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width,user-scalable=no">
    <title>Instagram Portfolio</title>
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700|Kaushan+Script|Montserrat' rel='stylesheet' type='text/css'>
    <link rel="stylesheets" type="text/css" href="stylesheets/posts.scss">
    <script type="text/javascript" src="js/modernizr.js"></script>
</head>
<body>
    <header>
        <%= image_tag "field.jpg" %>
        <div >
           <%= link_to "Michael Quintero", pages_about_path, {class: 'name fancy-font'} %>
        </div>
        <div class="titles">
            <h1>Hello! <span>I'm Michael</span></h1>
            <h2>I love to travel all around the world and design beautiful things</h2>
        </div>
        <div class="social">
            <a class="facebook" href="#">Facebook</a>
            <a class="twitter" href="#">Twitter</a>
            <a class="instagram" href="#">Instagram</a>
        </div>
    </header>
    <!-- navbar -->
    <div class="container-fluid">
    <div class="row">
        <!-- <div class="col-3 col-sm-2 col-md-2 col-lg-1 col-xl-1"> -->
        <div class="col-xl-1 col-lg-1 col-sm-2 col-md-2 col-3">
            <nav class="nav navbar-light navbar-toggleable-sm">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarWEX" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse flex-column mt-md-0 mt-4 pt-md-0 pt-4" id="navbarWEX">
                    <a class="nav-link navbar-brand active" href="~/Views/Forms/ControlPanel.cshtml"><span class="fa fa-home"></span></a>

                    <%= link_to "Instagram", pages_instagram_path, {class: 'nav-link'} %>
                    <%= link_to "Gallery", pages_gallery_path, {class: 'nav-link'} %>
                    <%= link_to "Contact", pages_contact_path, {class: 'nav-link'} %> 
                </div>
            </nav>
        </div>
       <!-- <div class="col-9 col-sm-10 col-md-10 col-lg-11 col-xl-11"> -->
        <div class="col-xl-11 col-lg-11 col-sm-10 col-md-10 col-9">
            <h2>Hello There</h2>
        </div>
    </div>
</div>
    <!--end of navbar -->
    <section class="instagram-wrap">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="instagram-content">
                        <h3>Latest Photos</h3>
                        <div class="row photos-wrap">
                        <!-- Instafeed target div -->
                        <div id="instafeed"></div>
                        <!-- The following HTML will be our template inside instafeed -->
                        <!-- <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                            <div class="photo-box">
                                <div class="image-wrap">
                                    <img src="images/test_img.jpg">
                                    <div class="likes">309 Likes</div>
                                </div>
                                <div class="description">
                                    Fantastic Architecture #architecture #testing
                                    <div class="date">September 16, 2014</div>
                                </div>
                            </div>
                        </div> -->

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                <h4>Get in touch</h4>
                <p class="about-text">I shoot, design and write. Don't hesitate and get in touch with me if you need some creative work done. I always work to achieve my best and fulfil client needs</p>
                <%= link_to "Contact Now", pages_contact_path, {class: 'contact-now-btn'} %>
                </div>
            </div>
        </div>
    </footer>
    <section class="footer-bottom">
        2018 &copy; Michael Quintero. All rights reserved.
    </section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.js"></script>
    <script type="text/javascript" src="js/instafeed.min.js"></script>
    <script type="text/javascript" src="js/app.js"></script>
</body>
</html>

<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>